"""SVM Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13q8GyNOs1OMqIjk4dDmMribLGmzj0o8C
"""

root_folder = '~/'

import pandas as pd

train = root_folder + 'train/train.csv'
data = pd.read_csv(train)

data['ID'] = data['ID'].map({'mono': 0, 'fibr': 1}).astype(int)
data.drop(['intensity'], axis=1, inplace=True)

x_train = data.drop(['ID'], axis=1)
y_train = data['ID']

from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

model = make_pipeline(StandardScaler(), SVC(gamma='auto', kernel='rbf'))
model.fit(x_train, y_train)

test_folder = root_folder + 'test/*'
import glob
import re
test_array = []

for f in glob.glob(test_folder):
  temp = pd.read_csv(f)
  temp.replace('mono.*', int(0) ,regex=True, inplace = True)

  temp.replace('fibr.*', int(1) ,regex=True, inplace = True)
  temp['ID'] = temp['ID'].map({0 : 0, 1 : 1}).astype(int)
  temp.drop(['intensity'], axis=1, inplace=True)
  test_array.append(temp)
  print('Loading: ' + f)

test_array[0].dtypes

from sklearn.metrics import accuracy_score
accuracy_array = []

for test in test_array:
  x_test = test.drop(['ID'], axis=1)
  y_test = test.drop(['G1', 'G2', 'S1', 'S2'], axis=1)
  y_predicted_test = model.predict(x_test)
  score = accuracy_score(y_test, y_predicted_test)
  accuracy_array.append(score)

import numpy as np

x = np.array(accuracy_array)
print(np.unique(x))

print(np.sum(x)/len(x))
